config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users,
                :path => '',
                :path_names => {:sign_in => "login", :sign_out => "deslogar", :edit => "perfil"},
                :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  post '/gratis' => 'charge#free'
  post '/pago' => 'charge#pago'
  post '/payment' => 'charge#payment'
  get '/meuscursos' => 'cursos#list'
  get '/subscriptions/:id' => "charge#show"
  post '/hook' => "charge#hook"
  put '/aulaconcluida' => 'aulas#proxima_aula'

   resources :cursos do
       resources :aula, only: [:show, :next_aula_point, :proxima_aula]
    end

    resources :curso do
        resources :reviews, only: [:create, :destroy]
    end

  root 'cursos#index'

end

app/models/curso.rb
class Curso < ActiveRecord::Base
  has_many :users, through: :viewedcourses
    extend FriendlyId
    friendly_id :name, use: [:slugged, :finders]

    belongs_to :trilha

    has_many :aulas
    has_many :reviews

    has_many :subscriptions
    has_many :users, through: :subscriptions

    validates :name, presence: true, length: { maximum: 50 }
    validates :content, presence: true
    validates :price, presence: true, numericality: {only_integer: true}

    def average_rating
        reviews.blank? ? 0 : reviews.average(:star).round(2)
    end
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
    before_action :authenticate_user!, only: [:list]

    
  def index
    @cursos = Curso.all
  end

  def show
      @curso = Curso.find(params[:id])
      @aulas = @curso.aulas.order(:tag)
      
      @joined = false
      
      if !current_user.nil? && !current_user.cursos.nil?
          @joined = current_user.cursos.include?(@curso)
      end
      
      @users = @curso.users.order('created_at').first(10)
      
      @review = Review.new
      @reviews = @curso.reviews
      @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
  end
    
  def list 
      if !current_user.nil?
          @cursos = current_user.cursos
      end 
  end
    
    def time_sum
        @aulatimesum = @aulas.sum(:time)
    end 
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_form.html.erb
<%= form_for(@curso) do |f| %>
  <% if @curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
      <% @curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :tag %><br>
    <%= f.text_field :tag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editing Curso</h1>

<%= render 'form' %>

<%= link_to 'Show', @curso %> |
<%= link_to 'Back', cursos_path %>

app/views/cursos/index.html.erb
<main class="content">
  <header class="intro-header index-header" style="background-image: url('https://static.pexels.com/photos/1139/black-and-white-city-skyline-buildings.jpg')">
      <div class="header-container">
        <div class="row">
          <div class="col-md-4">
            <%= image_tag("pug2.png") %>
          </div>
          <div class="col-md-8">
            <div class="row">
              <h1> Coloque seus projetos em Prática!</h1>
              <h4>Aprenda marketing digital e programação de uma forma que você pode começar a aplicar ainda hoje!</h4>
          </div>
        </div>
    </div>
  </header>
  <div class="clearfix"></div>

  <!-- <section id="index-subheader">
    <div class="col-md-6 col-xs-12 index-subheader-left">
      <div class="half-container">
        <h2> Marketing Digital </h2>
        <p> Aprenda sobre ferramentas e habilidades essenciais para começar no marketing digital. Desde o comecinho mesmo! </p>
        <ul>
          <li> Criar um website </li>
          <li> Rankear seu site no Google </li>
          <li> Comprar Mídia Digital </li>
          <li> Realizar Pesquisas de Mercado </li>
          <li> Leitura de dados e otimização </li>
          <li> Analytics e Estatística </li>
          <li> Taggeamento</li>
          <li> e mais.... </li>
        </ul>
      </div>
    </div>
    <div class="col-md-6 col-xs-12 index-subheader-right">
      <div class="half-container">
        <h2> Quem sou eu? </h2>
        <p> Eu sou o Bruno, um cara que cansou de aprender da forma padrão e decidiu ir a fundo em alguns assuntos para ensinar os outros, de forma gratuíta. Afinal o conhecimento é de todos, não. </p>
        <p> Além disso, sou Youtuber no Escolha Segura e trabalho com marketing digital nos projetos TattooFinder e Nutr </p>
        <ul>
          <li> Estatística </li>
          <li> Pesquisa de Mercado</li>
          <li> Normalização de bancos de dados </li>
        </ul>
      </div>
    </div>
  </section>
-->
  <section id="index-courses">
    <div class="container">
      <!--<h1 style="text-align: center; margin-bottom: 40px; font-size: 3.5em;"> CURSOS </h1>-->
          <% @cursos.in_groups_of(4) do |group| %>
          <div class="row">
          <% group.each do |curso| %>
            <% if curso %>
              <div class="col-md-3 col-sm-6 col-xs-12 panel-padding">
                  <div class="panel panel-default index-panel">
                      <!--<%= image_tag(curso.icon, class:'circleimgindex center') %>-->
                    <%= link_to curso do %>
                    <h3 class="course-title"><%= curso.name %></h3>
                    <% end %>
                    <p class="index-course-content"><%= truncate(curso.content, :length => 110) %></p>
                    <hr>
                    <div class="row">
                      <div class="col-xs-6 center">
                        <b><%= curso.aulas.sum(:time)/60 %>h</b> de curso
                      </div>
                      <div class="col-xs-6 center">
                        <b><%= curso.users.count %></b> Inscritos
                      </div>
                    </div>
                    <%= button_to "ACESSE AGORA!", curso, class:"btn btn-highlight", method: :get %>
                  <% end %>
                  </div>
                </div>
            <% end %>
           </div>
          <% end %>
          </div>
      </div>
  </div>
</main>

app/views/cursos/list.html.erb
<div class="background">
  <div class="container">
    <h1 class='center' style="margin-bottom: 40px; margin-top:40px;">Meus Cursos!</h1>


    <% if @cursos.count > 0 %>
        <div class="container">
        <% @cursos.in_groups_of(3) do |group| %>
        <div class="row">
        <% group.each do |curso| %>
          <% if curso %>
          <div class="col-md-4 col-sm-6 col-xs-12">
              <div class="panel panel-default index-panel">
                  <!--<%= image_tag(curso.icon, class:'circleimgindex center') %>-->
                <%= link_to curso do %>
                <h3><%= curso.name %></h3>
                <% end %>
                <p class="index-course-content"><%= truncate(curso.content, :length => 110) %></p>
                <hr>
                <div class="row">
                  <div class="col-xs-6 center">
                    <b><%= curso.aulas.sum(:time)/360 %>h</b> de curso
                  </div>
                  <div class="col-xs-6 center">
                    <b><%= curso.users.count %></b> Inscritos
                  </div>
                </div>
                <button class="btn btn-highlight" > COMEÇAR AGORA!</button>
              <% end %>
                </div>
              </div>
          <% end %>
         </div>
        <% end %>
    <% else %>
    <div class="center">
    <h5>Que peninha! Você ainda não está cadastrado em nenhum curso.</h5>
        <%= link_to "Encontrar Cursos", root_path, class: "btn-lg btn-primary" %>
    </div>
    <% end %>
      </div>
    </div>
</div>

app/views/cursos/new.html.erb
<h1>New Curso</h1>

<%= render 'form' %>

<%= link_to 'Back', cursos_path %>

app/views/cursos/show.html.erb
<% content_for :head do %>
<title><%= @curso.name %> | Studd</title>
	<!-- Twitter Card data -->

  <meta name="twitter:card" content="summary_large_image">
	<meta name="twitter:site" content="@Studd">
	<meta name="twitter:creator" content="@Studd">
	<meta name="twitter:title" content="<%= @curso.name %>">
	<meta name="twitter:description" content="<%= @curso.content %>">
	<meta name="twitter:image:src" content="<%= image_url @curso.image %>">

	<!-- Open Graph data -->
	<meta property="og:site_name" content="Studd">
	<meta property="og:type" content="www.studd.com.br">
	<meta property="og:title" content="<%= @curso.name %>">
	<meta property="og:description" content="<%= @curso.content %>">
	<meta property="og:image" content="<%= @curso.image %>">
<% end %>

<section id="show-course-header">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h1><%= @curso.name %></h1>
				<p><%= truncate(@curso.content, :length => 200) %></p>
        <br />
				<h6><b>Público Alvo:</b> <%= @curso.public %></h6>
				<h6><b>Requerimentos:</b><%= @curso.requeriment %> </h6>
        <br />
			</div>
		</div>
		<div class="row show-course-info-row">
			<div class="col-md-3 col-xs-6">
					<h2><%= @curso.average_rating %>/10</h2>
          <h5><%= @curso.reviews.count %> avaliações</h5>
			</div>
			<div class="col-md-3 col-xs-6">
					<!-- botar esse linha de código no modelo -->
          <h2><% onlyaula = @aulas.where(:section_header => false) %><%= onlyaula.count %></h2>
					<h5>Número de Aulas</h5>
			</div>
			<div class="col-md-3 col-xs-6">
					<h2><%= @aulas.sum(:time)/60 %>h</h2>
					<h5>Tempo de Curso </h5>
			</div>
			<div class="col-md-3 col-xs-6">
					<h2><%= @aulas.sum(:point) %></h2>
					<h5>Pontos Total</h5>
			</div>
	</div>
</div>


</section>
<section id="show-course-content">
	<div class="container">
		<div id="show-course-lessons">
		        <div class="col-md-8 course-show-content">
		                    <div class="">
		                        <% @aulas.each do |aula| %>
		                        <% if aula.section_header == true %>
		                        <h3 class="aulas-header">
		                            <%= aula.title %></h3>
		                        <% else %>
														<p><span class="border-circle"><%= aula.tag %></span><%= link_to aula.title, [aula.curso, aula], :class => "link-aula" %> <small class="aula-time"> | <%= aula.time %> minutos </small></p>
		                        <% end %>
		                      <% end %>
		                    </div>
		        </div>
	    </div>


	<div class="col-md-4 center cursosidebar">
			<div class="panel panel-default panel-show-course">
					<% if !@joined %>
							<h3><%= @curso.price == 0? "Grátis" : "R$#{@curso.price}" %></h3>

							<% if user_signed_in? %>
									<% if @curso.price == 0 %>
											<%= form_tag gratis_path do %>
											<%= hidden_field_tag 'curso_id', @curso.id %>
                      <p> Sim, você consegue acessar todas as informações deste curso de forma gratuíta!! <b> Aproveita!!</b> </p>
											<button type="submit" class="btn btn-highlight">Acessar este curso</button>
									<% end %>
									<% else %>
											<%= form_tag payment_path, id:'chargeForm' do %>
											<%= hidden_field_tag 'curso_id', @curso.id %>
											<button type="submit" class="btn btn-highlight">Comprar este curso Pago</button>
									<% end %>
									<% end %>
							<% else %>
									<%= link_to new_user_session_path do %>
									<button type="submit" class="btn btn-highlight">Faça Login para acessar!</button>
									<% end %>
							<% end %>
					<% else %>
          <%= image_tag('happy.png', size: "100" ) %>
          <h4 style="text-align: center;">Você já se inscreveu nesse curso!</h4>
          <%= link_to "Meus Cursos", meuscursos_path %>

					<% end %>
			</div>

      <div class="panel panel-default panel-review">
        <h3><b> ANÁLISE DO CURSO </b></h3>
      <br />
          <%= render 'shared/reviews' %>
      </div>
</section>

<br />


<!--
<div id="showdiv">
        <div class="col-md-9 showcontent">
                <p class="titulos"> Descrição do Curso </p>
                <p><%= @curso.content %></p>


                <p class="titulos"> Todas as Aulas </p>
                    <div class="list-group noborder margin20">
                        <% @aulas.each do |aula| %>
                        <% if aula.section_header == true %>
                        <a class="list-group-item active">
                            <%= aula.title %></a>
                        <% else %>
                        <%= link_to aula.title, [aula.curso, aula], :class => "list-group-item" %>
                        <% end %>
                        <% end %>
                        </div>
        </div>

        <div class="col-md-3 center cursosidebar">
            <div class="buythecourse">
                <% if !@joined %>
                    <h3><%= @curso.price == 0? "Grátis" : "R$#{@curso.price}" %></h3>

                    <% if user_signed_in? %>
                        <% if @curso.price == 0 %>
                            <%= form_tag gratis_path do %>
                            <%= hidden_field_tag 'curso_id', @curso.id %>
                            <button type="submit" class="btn paymentbutton">Acessar este curso Gratuíto</button>
                        <% end %>
                        <% else %>
                            <%= form_tag payment_path, id:'chargeForm' do %>
                            <%= hidden_field_tag 'curso_id', @curso.id %>
                            <button type="submit" class="btn btn-primary paymentbutton">Comprar este curso Pago</button>
                        <% end %>
                        <% end %>
                    <% else %>
                        <%= link_to new_user_session_path do %>
                        <button type="submit" class="btn btn-primary paymentbutton">Faça Login para acessar!</button>
                        <% end %>
                    <% end %>
                <% else %>
                    VOCÊ JÁ ESTÁ CADASTRADO NESTE CURSO NEGÃO!!
                    <div class="progress">
                    <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                <span class="sr-only" style="color:white">20% Complete</span>
                    </div>
                </div>
                <h6>Você já completou 20% do curso!</h6>
                <% end %>
            </div>
        <div class="cursosidebartop">FUNCIONALIDADES</div>
            <p>Downloads</p>
            <p>Reviews</p>


        <div class="cursosidebartop">SOBRE O PROFESSOR</div>
            <div class="row">
            <div class="col-md-4">
                <%= image_tag(@curso.profimage) %>
            </div>
            <div class="col-md-8">
                <a href="<%=@curso.proflink %>" class="profname"><%= @curso.profname %></a>
                <p class="profclass"><%= @curso.profdescription %></p>
            </div>
            </div>


            <div class="cursosidebartop">INSCRITOS (<%= @users.count %>)</div>
            <% @users.in_groups_of(4) do |group| %>
                    <% group.each do |u| %>
                    <div class="col-md-3">
				    </div>
					<% end %>
                <% end %>
        <br />
        <div class="cursosidebartop"> ANÁLISE DO CURSO </div>
        <br />
            <%= render 'shared/reviews' %>
            </div>

     <%= link_to 'Voltar', cursos_path %>
</div>